### ISSUE TITLE
Make the Like button work client-side

### ISSUE THREAD

**Issue by copyhacker** [goldnuggets24/Capybara#1]
> The "like" should be performed via some form of javascript/backend interaction.

**Comment by goldnuggets24** [comment]
This is added and will be pushed live later this evening. Now, the actions produced from homepage and top ten pages will render a 'picture' partial, which will be controlled remotely by this ajax action, that updates only the score: 

`$('.likes-<%= @picture.id %>').html('<%= @picture.score %> Likes');`
